seed: 0
model: lightgcn
# options: lightgcn, heterognn
data_dir: data_file
epochs: 20
dim: 64
layers: 2
batch_size: 4096
learning_rate: 0.001
weight_decay: 0.00001
valid_ratio: 0.1
checkpoint: outputs/checkpoints/best_model.pt
submission: outputs/submissions/Submission.csv
